Add namespace filtering
velp/netns-exporter pull request #3
Opened 2021-01-15 05:23 UTC by noevhlev

Add filtering of namespaces by regular expressions.

2021-01-23 10:38 UTC, velp requested changes

2021-01-23 10:38 UTC, velp commented on config.go
> +	cfg.NamespacesFilter.WhitelistRegexp = regexp.MustCompile(cfg.NamespacesFilter.WhitelistPattern)
Надо использовать `Compile` вместо `MustCompile` и возвращать нормальную ошибку. Паниковать в коде в логической ошибке - это плохой подход.

2021-01-23 10:38 UTC, velp commented on collector.go
> +		tmp := nsFiles[:0]
Новый слайс с таким де типом лучше создавать через `make()`

2021-01-23 10:38 UTC, velp commented on collector.go
> +		tmp := nsFiles[:0]
Аналогично, должен быть make

2021-01-23 10:38 UTC, velp commented on collector.go
> +	if (c.config.NamespacesFilter.BlacklistRegexp.String() != "") ||
В конфиге уже есть строковое значение паттерна в переменных `BlacklistPattern`, `WhitelistPattern`. Так же можно проверять указатель Regexp. Нет смысла городить конструкцию с `String()`

2021-01-23 10:38 UTC, velp commented on collector.go
> +		nsFiles = tmp
Если у тебя одновременно в конфиге указан и `blacklist_pattern` и `whitelist_pattern` то этот код не будет работать. Потому что ты сначала отфильтруешь по black list и перезапишешь исходный слайс, потом ты уже не отфильтруешь по white list (https://github.com/velp/netns-exporter/pull/3/files#diff-f1c80b360812fd52bef43d56f3c4ef40853f02711810857332ccedfd9f463f79R223), так как исходный лист перезаписан. 
Чтобы оба фильтра работали одновременно, нельзя изменять исходный слайс, надо создавать отдельный, общий.

2021-01-23 10:38 UTC, velp commented on config.go
> +	WhitelistRegexp *regexp.Regexp
Можно сделать собственный врапер Umarshal чтобы прочитать и распарсить regexp. Но это опционально, работать будет и так.

2021-01-25 15:46 UTC, noevhlev commented on config.go
> +	cfg.NamespacesFilter.WhitelistRegexp = regexp.MustCompile(cfg.NamespacesFilter.WhitelistPattern)
Поправил.

2021-01-25 15:47 UTC, noevhlev commented on collector.go
> +		tmp := nsFiles[:0]
Поправил.

2021-01-25 16:09 UTC, noevhlev commented on collector.go
> +		nsFiles = tmp
Этот момент не совсем понял. 
При работе двух фильтров одновременно подразумевается следующее:
1. Слайс точно не должен содержать вхождений которые совпадают с регулярным выражением блеклиста
2. Оставшийся слайс фильтруется по регулярке вайтлиста

Тестил фильтры вместе и поочередно - все работает как и ожидается.

2021-01-25 16:25 UTC, velp commented on collector.go
> +		nsFiles = tmp
> Слайс точно не должен содержать вхождений которые совпадают с регулярным выражением блеклиста

Тогда твой парсер конфига должен проверять это. Вот совсем не очевидный момент. Либо надо делать поддержку фильтрации с перекрестными вхождениями (что я и подразумевал).

2021-01-25 16:26 UTC, velp commented on collector.go
> +		nsFiles = tmp
И на самом деле сделать фильтр который будет работать вне зависимости есть там перекрытие или нет гораздо проще, чем понять по регулярным выражениям есть перекрытие или нет :)

2021-01-25 21:25 UTC, noevhlev commented on config.go
> +	WhitelistRegexp *regexp.Regexp
Добавил кастомный Unmarshal.

2021-01-25 21:27 UTC, noevhlev commented on collector.go
> +		nsFiles = tmp
В README.md и config.example.yaml добавлены пояснения касательно приоритетов при одновременном использвание фильтров черного и белого списков.

2021-01-26 13:57 UTC, velp approved these changes

2021-01-26 13:57 UTC, merged